### ISSUE TITLE
Single-field search for native-only models

### ISSUE THREAD

**Issue by brettwillis** [arrowheadapps/strapi-connector-firestore#16]
For models that do not allow non-native queries (and search), allow a field to be elected for native search.

A search on such a model will fun a query for `==` on the given field, a primitive kind of search using native native Firestore queries only.

**Comment by tormenteddan** [comment]
Hey would love to contribute, can you provide more context of the scope of this issue? @brettwillis

**Comment by brettwillis** [comment]
@tormenteddan would be great to have your contributions.

If you look at this line below, a "search" query is emulated by applying an OR operation (`whereAny()`) on comapring the search term to all compatible attributes, and OR queries are not supported by Firestore, so this is emulated in `QueryableFirestoreCollection` by fetching *all* documents and then manually filtering the result. This operation will throw an error on models that have `allowNonNativeQueries == false`.

https://github.com/arrowheadapps/strapi-connector-firestore/blob/d28c891dc55ae5214c31a7b22e215ba93ae6f013/src/queries.ts#L75

I would propose to add a option, something like `searchAttribute: string` to `ModelOptions`, where one can nominate the name of one of the attributes. On models with `allowNonNativeQueries == false`, this and only this nominated attribute will be searched in a way that is natively supported by Firestore.

https://github.com/arrowheadapps/strapi-connector-firestore/blob/d28c891dc55ae5214c31a7b22e215ba93ae6f013/src/types.ts#L27

The native search operation could be a Firestore `"=="` query. For string/text attributes, it could also be a "begins with" sort of query, like below. This is the closest thing to "search" that I'm aware of Firestore natively supporting.

https://github.com/arrowheadapps/strapi-connector-firestore/blob/d28c891dc55ae5214c31a7b22e215ba93ae6f013/src/mount-models.ts#L313-L318
