### ISSUE TITLE
Bootstrap function in admin failed

### ISSUE THREAD

**Issue by aminta** [arrowheadapps/strapi-connector-firestore#29]
I run `export GOOGLE_APPLICATION_CREDENTIALS='./config/Timetracking inner test-97f38b6dda77.json' && strapi develop`

and I got:

`warn Your application doesn't have a super admin user.
Bootstrap function in admin failed
error Error: 3 INVALID_ARGUMENT: inequality filter property and first sort order must be the same: roles and __key__
    at Object.callErrorFromStatus (/path/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
`

` 
"dependencies": {
    "knex": "<0.20.0",
    "sqlite3": "^5.0.0",
    "strapi": "3.2.5",
    "strapi-admin": "3.2.5",
    "strapi-connector-bookshelf": "3.2.5",
    "strapi-connector-firestore": "^3.0.0-alpha.21",
    "strapi-plugin-content-manager": "3.2.5",
    "strapi-plugin-content-type-builder": "3.2.5",
    "strapi-plugin-email": "3.2.5",
    "strapi-plugin-upload": "3.2.5",
    "strapi-plugin-users-permissions": "3.2.5",
    "strapi-utils": "3.2.5"
`

**Comment by brettwillis** [comment]
Hi @aminta, try version `3.0.0-alpha.22` and let me know if it is resolved for you?

**Comment by aminta** [comment]
Yes, thanks!
