### ISSUE TITLE
Single / Multiple Type Images support

### ISSUE THREAD

**Issue by shtelzerartem** [arrowheadapps/strapi-connector-firestore#32]
Hey, @brettwillis 
Thank you a lot for moving forward firestore support for Strapi.
I've found several bugs and wanted to know, how can I help you to solve them.

Firstly, Image from StrapiUploadPlugin always returns array of objects. But the desired behavior — to return array, if Image is type of Multiple and an object if it is of type Single.

Secondly, I think it's problem with parsing nested objects.
Here is a structure:
- Dynamic zone 
  Component 

  -  Repeatable Component

    - Images Array

Instead of returning array of images objects it return array of references.

Here is a fragment from response.

```js
{
    Footer: [
        {
            __component: "shared.footer-default",
            Column: [
                {
                    Images: [
                        "upload_file/3By5RQEedQIGpJeYhnfn",
                        "upload_file/3By5R234525ssdfYhn31"
                    ],
                    Title: "INFORMATION"
                },
                {
                    Images: [
                        "upload_file/3By5RQEedQIGpJeYhnfn",
                        "upload_file/3By5R234525ssdfYhn31"
                    ],
                    Title: "PAYMENT METHODS"
                },
                {
                    Images: [
                        "upload_file/3By5RQEedQIGpJeYhnfn",
                        "upload_file/3By5R234525ssdfYhn31"
                    ],
                    Title: "GUARANTEE"
                },
                {}
            ],
        }
    ],
}
```

**Comment by brettwillis** [comment]
Hi @shtelzerartem, appreciate the report.

For your first issue, what is the API endpoint/URL that is returning the array? 

For your second issue, relations are currently only populated one level deep, because I didn't know how else it should behave. It looks like your images array is inside a repeatable component inside another dyanmic zone component, which will be why it isn't being populated.

We need to figure out what the proper behaviour should be by deciphering how the official database connectors are designed...
- does it populate `x` levels deep?
- does it populate ALL references, and how are infinite reference loops handled?

**Comment by shtelzerartem** [comment]
For right now, the MongoDB connector creating a table for each component. And in dynamic sections, it's handled like a reference to an object of a specific kind. 
![image](https://user-images.githubusercontent.com/20266461/102668692-34668a80-4195-11eb-9e11-b3fb2eca2cb2.png)

Inside components, if there is an array of components, it's represented as an array of references.
![image](https://user-images.githubusercontent.com/20266461/102668789-7f809d80-4195-11eb-93d6-9a830957d9fa.png)

**Comment by brettwillis** [comment]
Regarding how components are stored in Firestore (embedded, not in separate tables), I added some discussion here: https://github.com/arrowheadapps/strapi-connector-firestore#strapi-components-including-dynamic-zone-repeatable.

I feel that this is the best way, but I am open to discussion...?

Regardless of the detail implementation of how components are stored in the database, this Firestore connector should populate the references in a way such that the API response is identical to the other connectors, so it should make no difference to the API. If it is behaving differently, then this is a bug I need to fix in the logic of populating references.

I'm currently working on a significant revamp of how relations are handled (see #35), so hopefully I will resolve this behaviour issue in the process...

**Comment by brettwillis** [comment]
Hi @shtelzerartem , I have released `3.0.0-alpha.25`, which has a significant refactoring and many improvements. I think that relations have been fully implemented now.

Could you try it out and let me know if it solves this issue?

**Comment by shtelzerartem** [comment]
@brettwillis hi, I will check it asap.

**Comment by brettwillis** [comment]
@shtelzerartem have you had a chance to check this out?

**Comment by brettwillis** [comment]
@shtelzerartem I'm going to close this issue assuming it's fixed.

But please feel free to let me know if you have any further problem.
