### ISSUE TITLE
Prevent out-of-control quota usage

### ISSUE THREAD

**Issue by brettwillis** [arrowheadapps/strapi-connector-firestore#33]
The Strapi admin font end is designed to count the size of a collection when displaying the list of collection entries (it uses this to determine the number of pages).

A single such query can be disasterous for Firestore cost/quota usage, let alone many such queries during normal usage of the admin front end, because

- Firestore will acrue a read operation for every document that is counted
- If the collection being displayed is large (i.e. the a collection of users, which could be hundreds of thousands or even millions), then this will result in hundreds of thousands or millions of reads billed everytime the list is viewed

Consider also that the `/count` API could be used or abused by authorized users outside the admin fton end.

Also, this doesn't apply only to the `count()` API, but also `find()` and `search()` where the filters would return a large number of results.

## Proposal 1 (fallback limiting)

As a fallback in place of any better solution, I propose to add a `maxQuerySize` option to the settings (and also allow it to be overridden per model) which will enforce a maximum limit on all queries (including `count()`). 

- This is a fallback to prevent out-of-control quota usage for a single query
- It wouldn't prevent a large amount of quota usage for for multiple queries
- It would cause inconsistent/unexpected behaviour when the user actually wants to reliably count the exact collection size (arguably a bad idea anyway - a counter should be maintained instead)

The documentation would recommend always setting the lowest appropriate limit. 

Should there be a default limit? If so, what should it be?

## Proposal 2 (disable counting)

Apply a PR or patch to the Strapi font-end so it doesn't try to count collections at all. This would drastically reduce usage. 

Perhaps we include a proposed patch in the examples or documetation so that people can apply it if they wish. But a PR to Strapi with to make counting behaviour configurable would be far better.

Alternatively we could add an option to disable the `count()` API entirely in this connector, which would cause unexpected results in the font-end.

This in itself doesn't limit out-of-control usage for `find()` and `search()` APIs, so should be used in conjunction with proposal 1.

## Proposal 3 (automatically maintain a counter)

For every collection maintain a counter of the number of documents (see https://stackoverflow.com/a/49407570/1513557). This would only work for counting the total number of documents without any filter applied an would immediately become useless when a filter is applied.

**Comment by brettwillis** [comment]
I'm inclined to set the default limit for proposal 1 to `100`. The Strapi Admin paginates the list in groups of 10, so this would limit the list to 10 pages.

Also, `100` is a realatively typical default for pagination on many public APIs...

This default would make sense as a starting point for the basic user, and it is easily customisable.

**Comment by aksdevac** [comment]
This might make strapi behave differently for Firestore connector, pagination can't work properly without count & it is not possible to store count for each filter condition or search. 
Firestore should add support for O(1) count query,
See: https://github.com/googleapis/google-cloud-python/issues/5731

**Comment by brettwillis** [comment]
Closing this issue as, with #34, this issue has been migitgated to the extent possible within the connector. A better solution can only be achieved with modification to Strapi itself as proposed in strapi/strapi#8841.
