### ISSUE TITLE
Unknown dialect undefined

### ISSUE THREAD

**Issue by xero88** [arrowheadapps/strapi-connector-firestore#69]
I'm not able to `npm develop` the strapi.

I got an error : Unknown dialect undefined

```
const path = require("path");

module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "firestore",
      settings: {
        projectId: "foo-3ef77",
      },
      options: {
        // Connect to a local running Firestore emulator
        // when running in development mode
        useEmulator: env("NODE_ENV") == "development",
      },
    },
  },
});
```

**Comment by brettwillis** [comment]
Hi @xero88 what version of Strapi are you using, is it V4? Unfortunately, Strapi V4 does not support database connectors, and so this Firestore connector can only be used with Strapi V3.

Hopefully at some point in the future, Strapi will again support database connectors. Read more [here](https://strapi.io/blog/mongo-db-support-in-strapi-past-present-and-future).
